---

language: python
python: "2.7"

sudo: required

# Enable the docker service
services:
  - docker

# Enable matrix builds
env:
  global:
    - DOCKER_STORAGE_DRIVER=vfs
  matrix:
    - MOLECULE_TARGET_DISTRO=centos
    - MOLECULE_TARGET_DISTRO=ubuntu

# Install the latest docker from apt.dockerproject.org
before_install:
  - sudo cat /etc/docker/daemon.json || true
  - sudo cat /etc/default/docker || true
  - sudo apt-get -qq update

# Install molecule
install:
  - pip install -r test-requirements.txt

# Execute the tests using the molecule docker driver
script:
  - docker info
  - molecule test --driver-name docker

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
