---

language: python
python: "2.7"

sudo: required

# Enable the docker service
services:
  - docker

# Enable matrix builds
env:
  matrix:
    - MOLECULE_TARGET_DISTRO=centos
    - MOLECULE_TARGET_DISTRO=ubuntu

# Replace aufs with the vfs docker storage driver
# to prevent systemd to fail starting docker in docker.
before_install:
  - sudo apt-get -qq update
  - sudo sed -i 's|DOCKER_OPTS=.*|DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock --storage-driver vfs"|g' /etc/default/docker
  - sudo service docker restart

# Install molecule
install:
  - pip install -r test-requirements.txt

# Execute the tests using the molecule docker driver
script:
  - docker info
  - molecule test --driver-name docker

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
