---

- name: Get list of labels.
  command: >-
         docker inspect
         --format {% raw %}'{{ range $key, $value := .Spec.Labels }}{{ printf "%s\n" $key }}{{ end }}'{% endraw %}
         {{ ansible_hostname }}
  register: docker_swarm_labels
  changed_when: false
  delegate_to: "{{ groups['docker_swarm_manager'][0] }}"
  delegate_facts: true
  tags:
    - swarm_labels

- name: Remove labels from swarm node.
  command: docker node update --label-rm {{ item }} {{ ansible_hostname }}
  with_items: "{{ docker_swarm_labels.stdout_lines }}"
  when: item not in swarm_labels
  delegate_to: "{{ groups['docker_swarm_manager'][0] }}"
  delegate_facts: true
  tags:
    - swarm_labels

- name: Assign labels to swarm nodes if any.
  command: docker node update --label-add {{ item }}=true {{ ansible_hostname }}
  when: item not in docker_swarm_labels.stdout_lines
  with_items:
    - "{{ swarm_labels  | default([]) }}"
  delegate_to: "{{ groups['docker_swarm_manager'][0] }}"
  delegate_facts: true
  tags:
    - swarm_labels
