---

- name: Add the Docker administrators to the Docker group.
  user:
    name: "{{ item }}"
    groups: "{{ docker_group_name }}"
    append: true
  register: addtogroup
  become: true
  with_items: "{{ docker_group_users }}"

- block:

    # See http://stackoverflow.com/a/37337848/1370301
    - name: Reset ansible connection after group changes (Ansible < 2.3.0).
      shell: "sleep 1; pkill -u {{ ansible_user }} {{ ssh_daemon }}"
      async: 3  # fail after 3 seconds of waiting
      poll: 2   # wait 2 seconds befor polling the task status
      failed_when: false  # suceed even if the command fails
      when: ansible_version is defined
        and (ansible_version.full is version_compare('2.3.0.0', '<'))

    # See https://stackoverflow.com/a/44753457
    - name: Reset ansible connection after group changes (Ansible >= 2.3.0).
      include_tasks: reset-connection.yml
      when: ansible_version is defined
        and (ansible_version.full is version_compare('2.3.0.0', '>='))

  when: ansible_connection in ['ssh', 'smart']
    and ansible_user is defined
    and ansible_user in docker_group_users
    and ansible_user in (addtogroup.results | selectattr('changed') | map(attribute='item') | list)
