---

- name: Prepare the test targets
  hosts: all
  tasks:
    - name: Make sure the ip command is available on Debian/Ubuntu.
      package:
        name: iproute2
        state: present
      when: ansible_os_family == 'Debian'

    - name: Make sure the ip command is available on RedHat/CentOS.
      package:
        name: iproute
        state: present
      when: ansible_os_family == 'RedHat'
