---

# Molecule Configuration
molecule_file: "{{ lookup('env','MOLECULE_FILE') }}"
molecule_scenario_directory: "{{ lookup('env','MOLECULE_SCENARIO_DIRECTORY') }}"
molecule_yml: "{{ lookup('file', molecule_file) | from_yaml }}"
molecule_driver_name: "{{ lookup('env', 'MOLECULE_DRIVER_NAME') | default('docker', true) }}"
molecule_target_distro: "{{ lookup('env','MOLECULE_TARGET_DISTRO') | default('centos', true) }}"

# Docker Driver Configuration
docker_image_name: "molecule_local/ansible-dockerswarm-{{ molecule_target_distro }}"
docker_image_file:
  centos: Dockerfile.centos
  ubuntu: Dockerfile.ubuntu
docker_command:
  centos: "/usr/sbin/init"
  ubuntu: "/sbin/init"

# Vagrant Driver Configuration
vagrant_base_image:
  centos: "centos/7"
  ubuntu: "bento/ubuntu-16.04"
