---

- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    molecule_file: "{{ lookup('env','MOLECULE_FILE') }}"
    molecule_yml: "{{ lookup('file', molecule_file) | from_yaml }}"
  tasks:

    # Docker Driver
    - block:
        - name: Destroy molecule Docker instance(s)
          docker_container:
            name: "{{ item.name }}-{{ molecule_yml.scenario.name }}"
            state: absent
          with_items: "{{ molecule_yml.platforms }}"
      when: molecule_yml.driver.name == 'docker'

    # Vagrant Driver
    - block:
        - name: Destroy molecule Vagrant instance(s)
          molecule_vagrant:
            instance_name: "{{ item }}-{{ molecule_yml.scenario.name }}"
            state: destroy
          with_items: "{{ molecule_yml.platforms }}"
      when: molecule_yml.driver.name == 'vagrant'
