---

dependency:
  name: galaxy

driver:
  name: docker     # The default molecule driver.
                   # Can be overriden from the CLI with the --driver-name option.
lint:
  name: yamllint   # Will use the rules defined in .yamllint

platforms:

  - name: ansible-dockerswarm-1
    groups:
      - docker_engine
      - docker_swarm_manager

  - name: ansible-dockerswarm-2
    groups:
      - docker_engine
      - docker_swarm_manager

  - name: ansible-dockerswarm-3
    groups:
      - docker_engine
      - docker_swarm_worker

provisioner:
  name: ansible
  playbooks:
    setup: ../common/create.yml
    teardown: ../common/destroy.yml
    converge: ../../playbook.yml
  lint:
    name: ansible-lint

scenario:
  name: swarm-cluster

verifier:
  name: testinfra
  lint:
    name: flake8
